VERSION = 'v1.2.1'

SOUND_VOLUME = 0.1

TIME_BETWEEN_TEXT = 0.3 # секунд
TIME_TO_LAST_TEXT_STAGE = 0.5 # секунд

TIME_TO_FIRST_DRON = 4 # секунд
TIME_BETWEEN_DRONS = 2 # секунд

FLASHING_IMAGE_TIME = 3 # секунд

NEW_DRON_SPEED_0 = 400
NEW_DRON_SPEED_MULT = 1.003

MAX_DRONS = 2
MAX_ROCKETS = 2

# Урон для каждого типа зданий
# НПЗ
REFINERY_DRON_DAMAGE = 10
REFINERY_OBLOMOK_DAMAGE = 5
REFINERY_ROCKET_DAMAGE = 20
# Резервуар
TANK_DRON_DAMAGE = 25
TANK_OBLOMOK_DAMAGE = 10
# Урон от ракеты для резервуара всегда 100
# ПВО
PVO_DRON_DAMAGE = 50
PVO_OBLOMOK_DAMAGE = 20
PVO_ROCKET_DAMAGE = 75

# Коэффициенты для вычисления счёта
STRIKE_COEFF          = 10
LOST_ROCKETS_COEFF    = 1
INDUSTRY_STRIKE_COEFF = 50
MISSED_DRONS_COEFF    = 5
DAMAGE_COEFF          = 0.1